### ISSUE TITLE
line breaks in CSV exported from Excel are not properly parsed 

### ISSUE THREAD

**Issue by paregorios** [isawnyu/geocollider#12]
Consider a file, saved from MSExcel for Mac (version 15) as "CSV UTF-8 (Comma delimited) (.csv)" (github won't let me attach CSV files?!, so a screenshot):

<img width="1253" alt="screen shot 2017-04-06 at 4 18 14 pm" src="https://cloud.githubusercontent.com/assets/263285/24775985/b28c94ee-1ae4-11e7-8f6a-f970d37f05d5.png">

Note the byte-order mark at start of the file (there's no mechanism in Excel for choosing to omit same). 

Here's what geocollider sees:

![screen shot 2017-04-06 at 4 21 44 pm](https://cloud.githubusercontent.com/assets/263285/24776126/2e0bfdbc-1ae5-11e7-9662-13c21400eacc.png)

**Comment by paregorios** [comment]
[geocollider-test.csv.zip](https://github.com/ryanfb/geocollider/files/904002/geocollider-test.csv.zip)

**Comment by paregorios** [comment]
FWIW, the same Excel file, opened in LibreOffice and saved as UTF8 CSV is handled perfectly by geocollider, but LibreOffice doesn't prepend a BOM.

**Comment by ryanfb** [comment]
So I realized in the course of this that there's actually two places that need to be fixed. One is the one I just pushed (which fixes the actual parsing/matching), the other is in the way `geocollider-sinatra` renders out the CSV preview: https://github.com/ryanfb/geocollider-sinatra/blob/master/geocollider-sinatra.rb#L86

I'll open an issue for that as well.
